from tqdm import tqdm
from psynet.lucid import get_lucid_service
from psynet.lucid.qualifications import create_lucid_recruitment_config
from psynet.utils import get_config


country_language_tags = (
    # ("TUR", "TR"),
    # ("GER", "DE"),
    ("FRE", "FR"),
    # ("JPN", "JP"),
    # ("ENG", "GB"),
    # ("ENG", "US"),
    # ("BEL", "BY"),
    # ("GER", "DE"),
    # ("DUT", "NL"),
    # ("FRE", "FR"),
    # ("SPA", "ES"),
    # ("ITA", "IT"),
    # ("FIN", "FI"),
    # ("CHI", "SG"),
    # ("CHI", "CN"),
    # ("KOR", "KR"),
    # ("ARA", "EG"),
    # ("GRE", "GR"),
    # ("BUL", "BG"),
    # ("CZE", "CZ"),
    # ("DAN", "DK"),
    # ("HRV", "HR"),
    # ("EST", "EE"),
    # ("HEB", "IL"),
    # ("HUN", "HU"),
    # ("LIT", "LT"),
    # ("NOR", "NO"),
    # ("POL", "PL"),
    # ("HIN", "IN"),
    # ("IND", "ID"),
    # ("JPN", "JP"),
    # ("POR", "PT"),
    # ("RUM", "RO"),
    # ("RUS", "RU"),
    # ("SRP", "RS"),
    # ("SLK", "SK"),
    # ("SLV", "SI"),
    # ("SWE", "SE"),
    # ("TUR", "TR"),
    # ("UKR", "UA"),
    # ("URD", "PK"),
    # ("ENG", "PK"),
    # ("VIE", "VN"),
    # ("THA", "TH"),
    # ("MAY", "MY"),
    # ("ENG", "AU"),
    ("ENG", "IN"),
    # ("ENG", "NG"),
    # ("SPA", "AR"),
    # ("SPA", "MX"),
    # ("SPA", "CO"),
    # ("SPA", "DO"),
    # ("SPA", "BO"),
    # ("SWA", "KE"),
    # ("SWA", "TZ"),
    # ("TGL", "PH"),
    # ("AFR", "ZA"),
    # ("AMH", "ET"),
    # ("ARA", "SA"),
    # ("ARA", "AE"),
    # ("ARA", "QA"),
    # ("ARA", "KW"),
    # ("BEN", "IN"),
    # ("FRE", "CA"),
    # ("FRE", "CH"),
    # ("FRE", "BE"),
    # ("FRE", "CM"),
    # ("LAT", "LV"),
    # ("POR", "BR"),
    # ("ZUL", "ZA"),
    # ("BUR", "MM"),
    # ("ICE", "IS"),
    # ("KAZ", "KZ"),
    # ("LTZ", "LU"),
    # ("ALB", "AL"),
    # ("AZE", "AZ"),
    # ("BOS", "BA"),
    # ("KHM", "KH"),
    # ("KUR", "IQ"),
    # ("LAO", "LA"),
    # ("MAC", "MK"),
    # ("MLT", "MT"),
    # ("NEP", "NP"),
    # ("PAN", "PK"),
    # ("SOT", "LS"),
    # ("UZB", "UZ"),
    # ("ENG", "ZA"),



    # ("FRE", "CA"),
    # ("FIN", "FI"),
    # ("EST", "EE"),
    # ("SPA", "AR"),
    # ("SPA", "CO"),
    # ("SPA", "DO"),
    # ("ENG", "AU"),
    # ("ENG", "GB"),
    # ("GRE", "GR"),
    # ("DAN", "DK"),
    # ("BUL", "BG"),

    # ("ENG", "SG"),
    # ("ARA", "LB"),
    # ("BEN", "BD"),
    # ("SPA", "CL"),
    # ("ENG", "GH"),
    # ("SPA", "PA"),
    # ("SPA", "UY"),
    # ("LAT", "LV"),
    # ("SPA", "CR"),
    # ("SPA", "GT"),
    # ("SPA", "EC"),

    # ("ARA", "MA"),
    # ("SPA", "PE"),
    # ("ARA", "SA"),
    # ("UKR", "UA"),
    # ("TGL", "PH"),
    # ("THA", "TH"),
    # ("SRP", "RS"),
    # ("SLV", "SI"),
    # ("SLK", "SK"),
    # ("POR", "PT"),
    # ("NOR", "NO"),
    # ("DUT", "NL"),
    # ("CZE", "CZ"),
    # ("MAY", "MY"),
    # ("LIT", "LT"),
    # ("HUN", "HU"),
    # ("HRV", "HR"),
    # ("HEB", "IL"),
    # ("SPA", "MX"),
)


config = get_config()
service = get_lucid_service(config=config)


qualifications_dict = {
    **service.get_qualifications_dict(),
    "TIMEOUT": service.get_qualifications_dict()["TIMEOUT v1"],
    # "LIVE_IN_COUNTRY v1": 223200,
    # "HAS_AUDIO v1": 223188,
    # "BORN_IN_COUNTRY v1": 223178,
    # "HAS_NATIONALITY v1": 223205,
    # 'IS_NATIVE V1': 223187,
    # 'MONOLINGUALISM v1': 223176,
    # 'TIMEOUT v1': 223198,
}


for language_tag, country_tag in tqdm(country_language_tags):
    config_path = f"qualifications/lucid/lucid-{language_tag}-{country_tag}.json"


    create_lucid_recruitment_config(
        language_tag=language_tag,
        country_tag=country_tag,
        question_answer_dict={
            "IS_NATIVE V1": ["Yes"],
            # "MONOLINGUALISM v1": ["I was raised with my native language only"],
            # "BORN_IN_COUNTRY v1": ["Yes"],
            # "LIVE_IN_COUNTRY v1": ["Yes"],
            "HAS_NATIONALITY v1": ["Yes"],
            # "HAS_AUDIO v1": ["Yes"],
        },
        config_path=config_path,
        debug=True,
        config=config,
        service=service,
        qualifications_dict=qualifications_dict,
    )
