import os
import numpy as np

RNG = np.random.default_rng(42)

ENDOWMENT = 10
COIN_VALUE_DOLLARS = 0.01
NUMBER_OF_ROUNDS = int(os.environ.get('ULTIMATUM_ROUNDS_REQUIRED', '3' if os.environ.get('PSYNET_PROFILE') == 'minimal' else '10'))
MAX_TIMEOUT_ROUNDS = int(os.environ.get('ULTIMATUM_MAX_TIMEOUTS', '5'))
MAX_ATTEMPTED_ROUNDS = NUMBER_OF_ROUNDS + MAX_TIMEOUT_ROUNDS + 1

PROPOSER_TIMEOUT = int(os.environ.get('ULTIMATUM_PROPOSER_SECONDS', '30'))
RESPONDER_TIMEOUT = int(os.environ.get('ULTIMATUM_RESPONDER_SECONDS', '30'))
FEEDBACK_TIMEOUT = int(os.environ.get('ULTIMATUM_FEEDBACK_SECONDS', '4'))
WAIT_PAGE_TIME = float(os.environ.get('ULTIMATUM_WAIT_SECONDS', '1.0'))
TIMEOUT_WAITING_FOR_OTHER = int(os.environ.get('ULTIMATUM_WAIT_FOR_OTHER_SECONDS', '120'))

BOT_TIMEOUT_STAGE = os.environ.get('ULTIMATUM_BOT_TIMEOUT_STAGE', '').strip().lower()

TIME_ESTIMATE_PER_ROUND = PROPOSER_TIMEOUT + RESPONDER_TIMEOUT + FEEDBACK_TIMEOUT + 5
ESTIMATED_DURATION = 8
BASE_PAYMENT = '0.25'
HOURLY_PAYMENT = 12
CURRENCY = '$'
TARGET_PARTICIPANTS = 20
ULTIMATUM_CHANNEL = 'ultimatum_game'
