import os

ENDOWMENT = 10
COIN_VALUE_DOLLARS = 0.01
ROUNDS_REQUIRED = int(os.environ.get('ULTIMATUM_ROUNDS_REQUIRED', '3' if os.environ.get('PSYNET_PROFILE') == 'minimal' else '10'))
PROPOSER_SECONDS = int(os.environ.get('ULTIMATUM_PROPOSER_SECONDS', '30'))
RESPONDER_SECONDS = int(os.environ.get('ULTIMATUM_RESPONDER_SECONDS', '30'))
FEEDBACK_SECONDS = int(os.environ.get('ULTIMATUM_FEEDBACK_SECONDS', '4'))
MAX_TIMEOUTS = int(os.environ.get('ULTIMATUM_MAX_TIMEOUTS', '5'))
GROUP_TYPE = 'ultimatum_game'
GLOBAL_CHANNEL = 'ultimatum_game'
BASE_PAYMENT = '0.25'
HOURLY_PAYMENT = 12
CURRENCY = '$'
ESTIMATED_DURATION = 8
TARGET_PARTICIPANTS = 20
