# This file is autogenerated with reference to psynet/resources/experiment_scripts/test.py.

# To run this test via Docker, run the following in your terminal:
#
# bash docker/run pytest test.py

# You can customize the behavior of the automated tests by overriding certain methods within
# your experiment class, located in experiment.py:
# - test_experiment
# - test_serial_run_bots
# - test_check_bots
# - test_check_bot

import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(__file__))

from experiment import (
    PORTFOLIO_TASK,
    build_messages,
    call_openrouter,
    check_model_available,
    normalize_website_html,
    openrouter_config,
)

pytest_plugins = ["pytest_dallinger", "pytest_psynet"]
experiment_dir = os.path.dirname(__file__)


@pytest.mark.parametrize("experiment_directory", [experiment_dir], indirect=True)
def test_experiment(launched_experiment):
    # NOTE:
    # If pytest reports a failure and prints these lines in your traceback
    # without printing the actual lines within `test_experiment` that raised the error,
    # you may be suffering from a bug in PyCharm's test reporting. To fix this,
    # we recommend either running the test externally (`psynet test local`)
    # or editing your PyCharm run configuration to add `--tb=short` to your additional
    # arguments. This should ensure that the full traceback is printed.
    launched_experiment.test_experiment()


def test_fallback_without_api_key(monkeypatch):
    monkeypatch.delenv("OPENROUTER_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    result = call_openrouter(
        "Make the hero warmer and add three product-design projects.",
        PORTFOLIO_TASK,
    )
    assert result["backend"] == "fallback_bot_response"
    assert result["fallback_reason"] == "api_key_missing"
    assert result["model_availability"]["available"] is False
    assert result["ai_request_config"]["api_key_present"] is False
    assert "Authorization" not in str(result["ai_request_payload"])
    assert "Alex Morgan" in result["generated_website"]


def test_model_availability_without_api_key(monkeypatch):
    monkeypatch.delenv("OPENROUTER_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    config = openrouter_config()
    assert check_model_available(config) == {
        "available": False,
        "reason": "api_key_missing",
    }


def test_normalize_website_html_removes_active_content():
    normalized = normalize_website_html(
        "<html><body><h1 onclick='x()'>Hi</h1><script>alert(1)</script></body></html>"
    )
    assert "<script" not in normalized["html"].lower()
    assert "onclick" not in normalized["html"].lower()
    assert "removed_active_content" in normalized["warnings"]


def test_build_messages_uses_selected_context():
    messages = build_messages("Improve contrast.", "<html>selected website</html>")
    assert messages[0]["role"] == "system"
    assert "Improve contrast." in messages[1]["content"]
    assert "selected website" in messages[1]["content"]
