# This file is autogenerated with reference to psynet/resources/experiment_scripts/test.py.

# To run this test via Docker, run the following in your terminal:
#
# bash docker/run pytest test.py

# You can customize the behavior of the automated tests by overriding certain methods within
# your experiment class, located in experiment.py:
# - test_experiment
# - test_serial_run_bots
# - test_check_bots
# - test_check_bot

import os

import pytest

from experiment import (
    bot_response,
    build_color_stimulus,
    build_human_prompt_html,
    format_ai_prompt,
    get_hybrid_config,
    parse_ai_slider_response,
    plan_ai_launches,
    request_openrouter_content,
)

pytest_plugins = ["pytest_dallinger", "pytest_psynet"]
experiment_dir = os.path.dirname(__file__)


def test_hybrid_config_validation(monkeypatch):
    settings = get_hybrid_config(
        {
            "ai_participant_proportion": "50",
            "ai_total_participant_target": "8",
            "openrouter_api_key_env_var": "OPENROUTER_API_KEY",
            "openrouter_model": "openai/gpt-4o-mini",
            "openrouter_base_url": "https://openrouter.ai/api/v1/chat/completions",
            "openrouter_timeout_seconds": "10",
            "openrouter_max_retries": "2",
            "openrouter_mock_mode": "true",
        }
    )
    assert settings["ai_participant_proportion"] == 50
    assert settings["openrouter_mock_mode"] is True

    with pytest.raises(ValueError, match="between 0 and 100"):
        get_hybrid_config({**settings, "ai_participant_proportion": 101})

    with pytest.raises(ValueError, match="requires the configured API key"):
        get_hybrid_config({**settings, "openrouter_mock_mode": False})

    monkeypatch.setenv("OPENROUTER_API_KEY", "test-key")
    assert get_hybrid_config({**settings, "openrouter_mock_mode": False})


def test_scheduler_plans_pure_human_mixed_and_all_ai():
    assert (
        plan_ai_launches(
            human_count=4,
            ai_count=0,
            ai_running=0,
            total_participant_target=6,
            ai_participant_proportion=0,
        )
        == 0
    )
    assert (
        plan_ai_launches(
            human_count=1,
            ai_count=0,
            ai_running=0,
            total_participant_target=20,
            ai_participant_proportion=50,
        )
        == 1
    )
    assert (
        plan_ai_launches(
            human_count=1,
            ai_count=1,
            ai_running=0,
            total_participant_target=20,
            ai_participant_proportion=50,
        )
        == 0
    )
    assert (
        plan_ai_launches(
            human_count=0,
            ai_count=0,
            ai_running=0,
            total_participant_target=6,
            ai_participant_proportion=100,
        )
        == 6
    )
    assert (
        plan_ai_launches(
            human_count=3,
            ai_count=0,
            ai_running=0,
            total_participant_target=4,
            ai_participant_proportion=75,
        )
        == 1
    )


def test_prompt_uses_same_stimulus_as_human_display():
    stimulus = build_color_stimulus(
        target="tree",
        participant_group="A",
        active_index=1,
        starting_values=[10, 20, 30],
    )
    human_prompt = build_human_prompt_html(stimulus)
    ai_prompt = format_ai_prompt(stimulus)

    assert "Participant group = A" in human_prompt
    assert "Participant group = A" in ai_prompt
    assert "tree" in human_prompt
    assert "tree" in ai_prompt
    assert "green" in ai_prompt
    assert "red=10, green=20, blue=30" in ai_prompt


def test_ai_response_parsing_and_mock_bot_response():
    assert parse_ai_slider_response('{"value": 127}') == 127
    assert parse_ai_slider_response("value: 42") == 42

    with pytest.raises(ValueError):
        parse_ai_slider_response('{"value": 300}')
    with pytest.raises(ValueError):
        parse_ai_slider_response('{"value": 10, "extra": true}')

    stimulus = build_color_stimulus(
        target="banana",
        participant_group="B",
        active_index=2,
        starting_values=[1, 2, 3],
    )
    response = bot_response(stimulus, {"openrouter_mock_mode": True})
    assert 0 <= response.answer <= 255
    assert response.metadata["participant_role"] == "ai"
    assert response.metadata["ai_stimulus"]["target"] == "banana"


def test_openrouter_request_wrapper_parses_stub(monkeypatch):
    monkeypatch.setenv("OPENROUTER_API_KEY", "test-key")
    settings = get_hybrid_config({"openrouter_mock_mode": False})

    def stub(request, timeout):
        assert request.full_url == settings["openrouter_base_url"]
        assert timeout == settings["openrouter_timeout_seconds"]
        assert request.headers["Authorization"] == "Bearer test-key"
        return {"choices": [{"message": {"content": '{"value": 9}'}}]}

    content = request_openrouter_content("prompt", settings, request_fn=stub)
    assert parse_ai_slider_response(content) == 9


@pytest.mark.parametrize("experiment_directory", [experiment_dir], indirect=True)
def test_experiment(launched_experiment):
    # NOTE:
    # If pytest reports a failure and prints these lines in your traceback
    # without printing the actual lines within `test_experiment` that raised the error,
    # you may be suffering from a bug in PyCharm's test reporting. To fix this,
    # we recommend either running the test externally (`psynet test local`)
    # or editing your PyCharm run configuration to add `--tb=short` to your additional
    # arguments. This should ensure that the full traceback is printed.
    launched_experiment.test_experiment()
